### ISSUE TITLE
PR#4 when reloading an html page that's served via the Ctx.HTML or Ctx.Template funcs it repeats it's content

### ISSUE THREAD

**Issue by dpouris** [dpouris/goster#5]
When reloading an html page that's served via the Ctx.HTML or Ctx.Template funcs it repeats it's content. With a result like this:

https://user-images.githubusercontent.com/7901125/209412144-69c3f21c-8201-4696-b071-e7dab1e13b68.mp4

You can find the code related to this in the 4th PR inside of goster/context.go:28 (func Template) and goster/context.go:47 (func HTML)

**Comment by mkopriva** [comment]
You are sharing state all over the place and in most instances you really shouldn't. Some of the consequences of the careless sharing of state are:
- repeated printing of the html file
- data race
- eventually your program will run out of memory and crash

**Comment by mkopriva** [comment]
Every time you receive a request to [`/hey`](https://github.com/dpouris/goster/blob/context-funcs/examples/example.go#L119) you call [`TemplateDir`](https://github.com/dpouris/goster/blob/context-funcs/examples/example.go#L120) which calls [`SetTemplateDir`](https://github.com/dpouris/goster/blob/c0603fb2c5d9fd476ba6518063108792f04333f4/goster.go#L170) which [appends to a shared slice in the config](https://github.com/dpouris/goster/blob/c0603fb2c5d9fd476ba6518063108792f04333f4/engine.go#L80).

That means that 5 requests to `/hey` will cause the `e.Config.FilePaths` to contain 5 sets of the same files as they were found by [`os.ReadDir`](https://github.com/dpouris/goster/blob/c0603fb2c5d9fd476ba6518063108792f04333f4/engine.go#L72). [Subsequently](https://github.com/dpouris/goster/blob/context-funcs/examples/example.go#L126) you grab [all those files](https://github.com/dpouris/goster/blob/c0603fb2c5d9fd476ba6518063108792f04333f4/context.go#L48) and [write each one that matches](https://github.com/dpouris/goster/blob/c0603fb2c5d9fd476ba6518063108792f04333f4/context.go#L67).

**Comment by mkopriva** [comment]
I would suggest that you **thoroughly** familiarize yourself with Go pointers; that you learn how requests are handled by the underlying `net/http.Server`; and that you think of any state as *potentially __unsafe for concurrency__* unless explicitly stated otherwise.

**Comment by dpouris** [comment]
there's one goster.Ctx instance in total instead there should be context in every single request
